# Running UI and API tests in separate docker containers
# To execute this docker-compose yml file use `docker compose -f run-tests-in-jenkins-in-volume.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f run-tests-in-jenkins-in-volume.yml down`

version: '3'
services:
  jenkins:
    image: myjenkins-dotnet
    container_name: jenkins
    build:
      context: ./JenkinsSettings
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
